new memes + better doc
paulborm/soundboard pull request #9
Opened 2020-03-29 20:04 UTC by mash1t

Hey @paulborm,
here are some new memes for the soundboard, hope you enjoy them.

Ohhhhhh may be a bit too long if sb. decides to spam it as it get's loud during a few stacked playbacks. Maybe this one can be removed.

2020-03-30 07:05 UTC, paulborm commented
Hi @mash1t 
can you please check the length and file size of your sounds and images again?  I know there are no guidelines but they should be as small as possbile.
You can achieve by:
- images: use jpg and compress the hell out of it using [imageoptim](https://imageoptim.com/mac) with the lowest possible quality setting and max width of around 500px. Goal should be a file under 10kb (it depends)
- sounds:  length between 1-2 seconds. Crop it if possible and compression (readme)[https://github.com/paulborm/soundboard#image-and-audio-compression]

Other changes:
- package.json is great
- .env is great
- not sure about the `now` part beause it's not necessary for development - maybe remove it until there is a real deployment :D

Thanks ❤️

2020-03-30 18:53 UTC, mash1t commented
@paulborm images have been resized to 512px width, sound files are now 48k (only ba-dum-tss.mp3 being 64k). 
It would be great if you could have another look at the changes, thank you.

2020-03-31 18:22 UTC, paulborm requested changes
Two last changes and we can merge

2020-03-31 18:22 UTC, paulborm commented on README.md
> +```
Please remove the now part

2020-03-31 18:22 UTC, paulborm commented on client/now.json
> -}
Please undo deletion of `now.json` file

2020-03-31 18:54 UTC, mash1t commented on README.md
> +```
done

2020-03-31 18:54 UTC, mash1t commented on client/now.json
> -}
done

2020-03-31 19:02 UTC, merged